# NumPy Arrays

In [1]:
import numpy as np 

In [2]:
my_list = [1,2,3] #making a list

In [4]:
arr = np.array(my_list) #turning list into array

In [5]:
arr  #1D array/vector

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]] #making list for 2D array

In [14]:
np.array(my_mat) #turning into 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0, 11, 2)  

#commonly used syntax for making array
#np.arange(low,high,step)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
np.zeros(3) 

#making 1D arrays with zeros

array([0., 0., 0.])

In [19]:
np.zeros((5,5)) 

#making 2D arrays with zeros

#(rows,columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.linspace(0,5,5) 

#10 evenly spaced point from 0 to 5

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [27]:
np.eye(4) 

#identity matriecs : diagonal of 1s  + squares

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
np.random.rand(5) 

#random with value in 0 to 1

array([0.83375839, 0.32040088, 0.53548684, 0.19040193, 0.81023387])

In [31]:
np.random.rand(5,5)

array([[0.62292319, 0.49121897, 0.76346449, 0.6745084 , 0.95257241],
       [0.71006474, 0.69384138, 0.67970635, 0.67607882, 0.6982895 ],
       [0.46595566, 0.56646641, 0.96208503, 0.60425454, 0.444413  ],
       [0.61117917, 0.37944743, 0.5591944 , 0.67774149, 0.89990281],
       [0.34376014, 0.85411738, 0.46236179, 0.58770524, 0.79742422]])

In [35]:
np.random.randn(2) 

# standard normal distribution 1D

array([0.14101796, 0.58092724])

In [34]:
np.random.randn(4,4)

array([[ 4.30902339e-01, -4.09673058e-01, -3.27360284e-01,
        -2.14666680e-01],
       [-1.61224875e+00, -6.41748420e-04,  2.06934788e+00,
         4.61262474e-01],
       [ 2.64618067e-01, -2.12325014e+00,  5.54144068e-01,
         3.45732052e-01],
       [-6.06924981e-01,  7.57877607e-02, -2.66941585e+00,
        -8.04757787e-01]])

In [144]:
np.random.randint(1,100,(6,8)) 

# array with random int from 1 to 99

array([[76, 11,  8, 54, 85, 63, 66, 14],
       [19, 10, 25,  8, 86, 60, 23, 34],
       [57, 59, 92, 30, 24, 36, 40, 77],
       [72, 19, 16, 81, 24, 79, 24, 65],
       [84, 81, 69, 26, 39, 40, 95, 94],
       [85, 42, 29, 99, 76, 19, 90, 29]])

In [152]:
arr = np.arange(25)

In [153]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [147]:
ranarr = np.random.randint(0,50,10)

In [148]:
ranarr

array([ 8, 45, 22,  9, 34, 25, 29, 35, 22,  6])

In [154]:
arr.reshape(5,5) 

#reshaping 1D into 2D Total size unchanged

# no. row * no. columns = actual no. of elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr.max()

40

In [48]:
ranarr.min()

5

In [49]:
ranarr

array([40, 35, 10, 30, 17,  5, 21, 30,  7, 27])

In [54]:
ranarr.argmax() #index of maximum value

0

In [51]:
ranarr.argmin()

5

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arr.shape

(25,)

In [55]:
arr.dtype

dtype('int32')

In [57]:
from numpy.random import randint

randint(2,10,2)

array([4, 8])

# NumPy Indexing and Selection

In [58]:
import numpy as np

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[8]

8

In [62]:
arr[2:3]

array([2])

In [64]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [65]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
arr[0:5] = 100 #setting value

In [69]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
arr = np.arange(11)

In [71]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arr = arr[0:6]

In [73]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [74]:
slice_of_arr[:] = 99 #broadcasting changes original array

In [75]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [76]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy = arr.copy()

In [78]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
arr_copy[:] = 100

In [80]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [81]:
#summary:
# arr : is a normal array
# slice_of_arr = arr[0:6] : this will broadcast the arr value
# changing anything in slice_of_arr will change arr value
# to copy an array
# arr_copy = arr.copy()
#changing copied array won't affect the original

In [82]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [83]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[0][0] #[row][column]

5

In [86]:
arr_2d[0]

array([ 5, 10, 15])

In [91]:
arr_2d[2,1]

40

In [99]:
arr_2d[:2,1:] 
#takes first two rows and column exclusive of first column

array([[10, 15],
       [25, 30]])

In [100]:
arr_2d[:2]   #it takes first two rows first two

array([[ 5, 10, 15],
       [20, 25, 30]])

In [101]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

### Conditional Selection

In [102]:
arr = np.arange(1,11)

In [103]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
bool_arr = arr>5 #comparison array makes it boolean array

In [109]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [110]:
arr[bool_arr] # will return True value of bool_arr

array([ 6,  7,  8,  9, 10])

In [112]:
arr[arr>5] #sem as above

array([ 6,  7,  8,  9, 10])

In [114]:
arr[arr<3]

array([1, 2])

In [115]:
arr_2d = np.arange(50).reshape(5,10)

In [116]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [119]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations

### Array with Array
### Array with Scalars
### Universal Array Functions

In [121]:
arr = np.arange(0,11)

In [122]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [124]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [125]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
arr + 100 #scalars

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [128]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [130]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [132]:
arr/arr

C:\Users\chgra\AppData\Local\Temp\ipykernel_11292\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
1/arr #inf signifies infinity 

C:\Users\chgra\AppData\Local\Temp\ipykernel_11292\2175640657.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr #inf signifies infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [135]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [136]:
#universal function

In [137]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [138]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [139]:
np.max(arr)

10

In [140]:
arr.max()

10

In [141]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [142]:
np.log(arr)

C:\Users\chgra\AppData\Local\Temp\ipykernel_11292\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [143]:
# for more see documentation